language: go

go:
  - "1.10.x"

git:
  depth: 1
 
before_install: go get -u github.com/spf13/cobra/cobra

script: go test -timeout 90s -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success: bash <(curl -s https://codecov.io/bash)
