language: go

go:
  - "1.10.x"

git:
  depth: 1

before_install:
  - go get -u github.com/spf13/cobra/cobra

script:
 - go test -v -covermode=count -coverprofile=coverage.out ./...
 - go test -v -covermode=atomic -coverprofile=coverage.txt ./...